### ISSUE TITLE
importing file using read_geno_dist

### ISSUE THREAD

**Issue by wittney** [mmollina/MAPpoly#1]
I have constructed a .dat file from the function in polyRAD (export_MAPpoly). When I input this file into the read_geno_dist function, I receive the error:

Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  scan() expected 'a real', got 'of'

Here is the file used in the function: https://uofi.box.com/s/mytl5xnza4rpcoic1rcwz31c6219indr

**Comment by mmollina** [comment]
The problem is in your phenotype format. 
The correct format would be: ﻿﻿
nphen 2
pheno---------------------------------------
Day_3_of_Cold_Treatment  0.68 0.64 ...
Second_phenotype value1 value2 ... value319

I am not quite sure what is the origin of your phenotypic observations in your dataset. Apparently, you have more observations than the number of individuals. Are those replicates? 
Anyway, the phenotypic information is not needed to build the map and, if you are having trouble with the format, you can add those later on in your analysis.

**Comment by wittney** [comment]
I fixed my file and it works.
Thank you for immediate response!

**Comment by wittney** [comment]
I fixed my file and it works!
Thank you for your immediate response.

**Comment by mmollina** [comment]
Great!
