### ISSUE TITLE
Triploids coming from a cross-population

### ISSUE THREAD

**Issue by KillianLrnt** [mmollina/MAPpoly#53]
Hello everyone!

I'm currently writing my final year dissertation, and I'm working on a QTL detection on a triploid bananas population. However, to achieve that, I need to produce a genetic map of my population. My hybrids are triploids and are coming from a cross-breeding between a tetraploid and a diploid. 

Knowing that, I would like to use MAPpoly on my population, but the function _read_geno_csv_ doesn't allow me to. Indeed, when I fill in the ploidy number with "3", there is an error message because my tetraploid parent possesses some 1/1/1/1 markers or tetraplex marker, with a dosage equal to 4. Same problem with "2" as the ploidy number (dosage "4" for my tetraploid parent, and "3" for my hybrids). Finally, if fill in the ploidy number with "4", it works, but the dosage of my hybrids are not correct anymore (a dosage "3", meaning 1/1/1, becomes 0/1/1/1).

Can you please help me with this situation? First of all, can MAPpoly handle a cross-population coming from a 4x*2x breeding?

Thank you very much!

**Comment by mmollina** [comment]
@KillianLrnt: odd ploidy levels are not implemented yet in MAPpoly. I have been planning to do it for a long time, but I have never had the opportunity. This issue is a good opportunity to implement it. I will most likely implement it by the end of August. I'll keep you posted on the progress, and if you could help me test the beta version would be great. Thanks.

**Comment by mmollina** [comment]
@KillianLrnt: odd ploidy levels are not supported in MAPpoly's current version. I have been planning to do it for a long time, but I have never had the chance. This issue is a good opportunity to implement it. I will most likely work on it by the end of August. I'll keep you posted on the progress, and if you could help me test the beta version would be great. Thanks.

**Comment by KillianLrnt** [comment]
My tetraploid parent is theoretically an autopolyploid, but since it was originaly a colchicine doubled-diploid, I supposed I could still consider it as an allopolyploid. As it was said in a previous closed issue, I still used your package, with "2" as the ploidy of both parents.
I'm supposed to finish my intership by the end of august, but I would be glad to test the beta version even if I'm done. It could be intersting comparing what I've found now with a ploidy = 2 to what we will find. If you want, I could put you in contact with my supervisor, a vegetal genetc researcher, for further details.
